=== MarianAmador/DocumentosXMLLL/src/DTD.dtd
<!ELEMENT Partidos (Fecha, Partido+)>
        <!ELEMENT Fecha (#PCDATA)>
        <!ELEMENT Partido (Equipos, Puntos, Goles+)>
        <!ELEMENT Equipos (local, Visitante)>
        <!ELEMENT local (#PCDATA)>
        <!ELEMENT Visitante (#PCDATA)>
        <!ELEMENT Puntos (#PCDATA)>
        <!ELEMENT Goles (Gol+)>
        <!ELEMENT Gol (Jugador, Tiempo)>
        <!ELEMENT Jugador (#PCDATA)>
        <!ELEMENT Tiempo (#PCDATA)>

=== MarianAmador/DocumentosXMLLL/src/XML.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE Partidos SYSTEM "DTD.dtd">
<Partidos>
    <Fecha>15-09-2023</Fecha>
    <Partido>
        <Equipos>
            <local>Mazatlan FC</local>
            <Visitante>Cruz Azul</Visitante>
        </Equipos>
        <Puntos>2-2</Puntos>
        <Goles>
            <Gol>
                <Jugador>Nicol√°s Benedetti</Jugador>
                <Tiempo>minuto 14</Tiempo>
            </Gol>

            <Gol>
                <Jugador>Bryan Colula</Jugador>
                <Tiempo>minuto 39</Tiempo>
            </Gol>

            <Gol>
                <Jugador>Diber Cambindo</Jugador>
                <Tiempo>minuto 48</Tiempo>
            </Gol>

            <Gol>
                <Jugador>Diber Cambindo</Jugador>
                <Tiempo>minuto 90 + 2</Tiempo>
            </Gol>
        </Goles>
    </Partido>

    <Partido>
        <Equipos>
            <local>Tijuana</local>
            <Visitante>Toluca</Visitante>
        </Equipos>
        <Puntos>2-1</Puntos>
        <Goles>
            <Gol>
                <Jugador>Carlos Gonzales</Jugador>
                <Tiempo>minuto 12</Tiempo>
            </Gol>

            <Gol>
                <Jugador>Fernando Madrigal</Jugador>
                <Tiempo>minuto 18</Tiempo>
            </Gol>

            <Gol>
                <Jugador>Carlos Gonzalez</Jugador>
                <Tiempo>minuto 12</Tiempo>
            </Gol>

            <Gol>
                <Jugador>Robert Morales</Jugador>
                <Tiempo>minuto 90 + 6</Tiempo>
            </Gol>
        </Goles>
    </Partido>
</Partidos>
